services:
  api:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - VITE_API_URL=http://api:8000
    depends_on:
      - api
    user: node