services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s; timeout: 5s; retries: 3
    ports:
      - "8000:8000"
    depends_on:
      - redis
    deploy:
      replicas: 3

  redis:
    image: redis:7-alpine
    sysctls:
      vm.overcommit_memory: "1"
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"
    command: npm run dev
    environment:
      - VITE_API_URL=http://api:8000
    depends_on:
      - api
    user: node

  locust:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "pip install --no-cache-dir locust && \
             locust -f tests/load/locustfile.py \
             --host http://api:8000 \
             --web-host 0.0.0.0"
    ports:
      - "8089:8089"
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend

  redis_exporter:
    image: oliver006/redis_exporter:v1.45.0
    command: --redis.addr=redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    ports:
      - "9113:9113"
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - redis_exporter
      - nginx_exporter

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3000:3000"
    depends_on:
      - prometheus