global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']