coverage:
  precision: 2
  round: down
  range: "70...100"
comment:
  layout: "header, diff, footer"
  behavior: default
ignore:
  - "frontend/node_modules/*"
  - "backend/.venv/*"
  - "__pycache__/*"
  - "*.pyc"