name: Generate OpenAPI Spec

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write

concurrency:
  group: generate-openapi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate OpenAPI YAML
        run: |
          cd backend
          python scripts/gen_openapi.py

      - name: Upload OpenAPI YAML
        uses: actions/upload-artifact@v3
        with:
          name: openapi-yaml
          path: docs/openapi.yaml

  commit:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download OpenAPI YAML
        uses: actions/download-artifact@v3
        with:
          name: openapi-yaml
          path: docs/openapi.yaml

      - name: Commit and Push Spec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/openapi.yaml
          git diff --cached --quiet || (git commit -m "ci: update OpenAPI spec" && git push)