name: Generate OpenAPI Spec

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate-openapi:
    name: Generate & Commit OpenAPI YAML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate OpenAPI YAML
        run: |
          cd backend
          python scripts/gen_openapi.py

      - name: Commit and Push Spec
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/openapi.yaml
          if ! git diff --cached --quiet; then
            git commit -m "ci: update OpenAPI spec (openapi.yaml)"
            git push
          else
            echo "No changes in openapi.yaml"
          fi